# Generated by Django 5.2.1 on 2025-07-18 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_company_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="related_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "manager_main"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
