# Generated by Django 5.2.1 on 2025-07-18 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_company_related_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("view_all_companies", "Can view all companies"),
                    ("view_assigned_companies", "Can view assigned companies"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="related_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["manager_main", "salesmanager_main"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
