# Generated by Django 5.2.4 on 2025-07-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_city_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_working_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Maximum 24 hours per day', max_digits=4, verbose_name='Daily Working Hours')),
                ('working_on_saturday', models.BooleanField(default=False, verbose_name='Working on Saturday')),
                ('working_on_sunday', models.BooleanField(default=False, verbose_name='Working on Sunday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='customer.company', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
                'ordering': ['customer__name'],
            },
        ),
    ]
