# Generated by Django 5.2.4 on 2025-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='daily_working_hours',
            field=models.PositiveSmallIntegerField(default=8, help_text='Maximum 24 hours per day', verbose_name='Daily Working Hours'),
        ),
    ]
