# Generated by Django 5.2.1 on 2025-08-02 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_workinghours_daily_working_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['company__name'], 'verbose_name': 'Adres', 'verbose_name_plural': 'Adresler'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Şehir', 'verbose_name_plural': 'Şehirler'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'permissions': [('view_all_companies', 'Can view all companies'), ('view_assigned_companies', 'Can view assigned companies')], 'verbose_name': 'Firma', 'verbose_name_plural': 'Firmalar'},
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['full_name'], 'verbose_name': 'İletişim Bilgileri', 'verbose_name_plural': 'İletişim Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='corebusiness',
            options={'ordering': ['name'], 'verbose_name': 'Ana İş Kolu', 'verbose_name_plural': 'Ana İş Kolu'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Ülke', 'verbose_name_plural': 'Ülkeler'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name'], 'verbose_name': 'İlçe', 'verbose_name_plural': 'İlçeler'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'Mahalle', 'verbose_name_plural': 'Mahalleler'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['customer__name'], 'verbose_name': 'Çalışma Saatleri', 'verbose_name_plural': 'Çalışma Saatleri'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customer.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.county', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='Merkez', max_length=100, verbose_name='Address Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('distributor', 'Distributor'), ('enduser', 'End User')], max_length=20, null=True, verbose_name='Company Type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='core_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.corebusiness', verbose_name='Core Business'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='related_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.company', verbose_name='Related Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='related_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['manager_main', 'salesmanager_main']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Related Manager'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='customer.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='corebusiness',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Core Business Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='country_flags/', verbose_name='Country Flag'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Türkiye', max_length=100, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='county',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100, verbose_name='County Name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.county', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='customer.company', verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='daily_working_hours',
            field=models.PositiveSmallIntegerField(default=8, help_text='Maksimum 24 saat, minimum 1 saat olmalıdır.', verbose_name='Günlük Çalışma Saatleri'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='working_on_saturday',
            field=models.BooleanField(default=False, verbose_name='Cumartesi Çalışması'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='working_on_sunday',
            field=models.BooleanField(default=False, verbose_name='Pazar Çalışması'),
        ),
    ]
