# Generated by Django 5.2.1 on 2025-07-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0001_initial"),
        ("customer", "0002_company_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.company",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manager_main", "Main Company Manager"),
                    ("salesmanager_main", "Main Company Sales Manager"),
                    ("service_main", "Main Company Service Personnel"),
                    ("manager_distributor", "Distributor Manager"),
                    ("salesmanager_distributor", "Distributor Sales Manager"),
                    ("service_distributor", "Distributor Service Personnel"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
