# Generated by Django 5.2.1 on 2025-07-18 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_company_customuser_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_assign_manager", "Can assign manager to company")
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
