# Generated by Django 5.2.1 on 2025-08-02 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_customuser_options'),
        ('customer', '0008_alter_address_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager_main', 'Main Company Manager'), ('salesmanager_main', 'Main Company Sales Manager'), ('service_main', 'Main Company Service Personnel'), ('manager_distributor', 'Distributor Manager'), ('salesmanager_distributor', 'Distributor Sales Manager'), ('service_distributor', 'Distributor Service Personnel')], max_length=32, null=True, verbose_name='Rol'),
        ),
    ]
