# Generated by Django 5.2.4 on 2025-07-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrantyvalue",
            name="value",
            field=models.FloatField(),
        ),
    ]
