# Generated by Django 5.2.4 on 2025-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_master", "0003_attributetype_attributeunit_inventoryitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="item_code",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="parent",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="production_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
