# Generated by Django 5.2.4 on 2025-07-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_master", "0004_remove_inventoryitem_item_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributeunit",
            options={
                "ordering": ["attribute_type__name", "name"],
                "verbose_name": "Attribute Unit",
                "verbose_name_plural": "Attribute Units",
            },
        ),
        migrations.AddField(
            model_name="attributeunit",
            name="attribute_type",
            field=models.ForeignKey(
                default=1,
                help_text="The attribute type this unit belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="item_master.attributetype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attributeunit",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="attributeunit",
            unique_together={("name", "attribute_type")},
        ),
    ]
