# Generated by Django 5.2.4 on 2025-07-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_master", "0005_update_attribute_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributeunit",
            name="attribute_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The attribute type this unit belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="item_master.attributetype",
            ),
        ),
    ]
