# Generated by Django 5.2.4 on 2025-07-20 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item_master", "0006_fix_attribute_unit_nullable"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventoryitemattribute",
            unique_together=set(),
        ),
    ]
