# Generated by Django 5.2.4 on 2025-07-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_master", "0007_fix_attribute_issues"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributeunit",
            options={
                "ordering": ["name"],
                "verbose_name": "Attribute Unit",
                "verbose_name_plural": "Attribute Units",
            },
        ),
        migrations.AlterUniqueTogether(
            name="attributeunit",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="attributeunit",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="attributeunit",
            name="symbol",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name="attributeunit",
            name="attribute_type",
        ),
        migrations.CreateModel(
            name="AttributeTypeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the default unit for this attribute type?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_units",
                        to="item_master.attributetype",
                    ),
                ),
                (
                    "attribute_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_types",
                        to="item_master.attributeunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Type Unit",
                "verbose_name_plural": "Attribute Type Units",
                "ordering": [
                    "attribute_type__name",
                    "-is_default",
                    "attribute_unit__name",
                ],
                "unique_together": {("attribute_type", "attribute_unit")},
            },
        ),
    ]
