# Generated by Django 5.2.4 on 2025-07-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0008_new_attribute_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Örn: Ay bazlı, Çalışma saati bazlı, Kilometre bazlı', max_length=100)),
                ('unit', models.CharField(help_text='Örn: ay, saat, km', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servis Periyodu Türü',
                'verbose_name_plural': 'Servis Periyodu Türleri',
            },
        ),
        migrations.CreateModel(
            name='ServicePeriodValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Örn: 6 ay, 3000 saat, 10000 km')),
                ('description', models.CharField(blank=True, help_text='Opsiyonel açıklama', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_period_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.serviceperiodtype')),
            ],
            options={
                'verbose_name': 'Servis Periyodu Değeri',
                'verbose_name_plural': 'Servis Periyodu Değerleri',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=True, help_text='Kritik bakım mı?')),
                ('maintenance_description', models.TextField(blank=True, help_text='Bakım açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='item_master.itemmaster')),
                ('service_period_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.serviceperiodvalue')),
            ],
            options={
                'verbose_name': 'Bakım Programı',
                'verbose_name_plural': 'Bakım Programları',
                'unique_together': {('item_master', 'service_period_value')},
            },
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='service_periods',
            field=models.ManyToManyField(blank=True, help_text='Bu ürün için geçerli servis periyotları', through='item_master.MaintenanceSchedule', to='item_master.serviceperiodvalue'),
        ),
    ]
