# Generated by Django 5.2.4 on 2025-07-25 16:12

import item_master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0009_serviceperiodtype_serviceperiodvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=item_master.models.get_qrcode_upload_path),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
