# Generated by Django 5.2.1 on 2025-07-27 16:51

import item_master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0010_alter_inventoryitem_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to=item_master.models.get_qrcode_upload_path),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
