# Generated by Django 5.2.1 on 2025-07-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0011_alter_inventoryitem_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitemattribute',
            unique_together={('inventory_item', 'attribute_type', 'unit')},
        ),
    ]
