# Generated by Django 5.2.1 on 2025-07-28 10:57

import django.db.models.deletion
import item_master.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0011_alter_inventoryitem_qr_code_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitemattribute',
            options={'ordering': ['attribute_type__name'], 'verbose_name': 'Inventory Item Attribute', 'verbose_name_plural': 'Inventory Item Attributes'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'Item Image', 'verbose_name_plural': 'Item Images'},
        ),
        migrations.AlterModelOptions(
            name='itemmaster',
            options={'verbose_name': 'Item Master', 'verbose_name_plural': 'Item Masters'},
        ),
        migrations.AlterModelOptions(
            name='itemsparepart',
            options={'verbose_name': 'Item Spare Part', 'verbose_name_plural': 'Item Spare Parts'},
        ),
        migrations.AlterModelOptions(
            name='itemspec',
            options={'verbose_name': 'Item Specification', 'verbose_name_plural': 'Item Specifications'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': 'Maintenance Schedule', 'verbose_name_plural': 'Maintenance Schedules'},
        ),
        migrations.AlterModelOptions(
            name='serviceform',
            options={'verbose_name': 'Service Form', 'verbose_name_plural': 'Service Forms'},
        ),
        migrations.AlterModelOptions(
            name='serviceperiodtype',
            options={'verbose_name': 'Service Period Type', 'verbose_name_plural': 'Service Period Types'},
        ),
        migrations.AlterModelOptions(
            name='serviceperiodvalue',
            options={'verbose_name': 'Service Period Value', 'verbose_name_plural': 'Service Period Values'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='stocktype',
            options={'verbose_name': 'Stock Type', 'verbose_name_plural': 'Stock Types'},
        ),
        migrations.AlterModelOptions(
            name='warrantytype',
            options={'verbose_name': 'Warranty Type', 'verbose_name_plural': 'Warranty Types'},
        ),
        migrations.AlterModelOptions(
            name='warrantyvalue',
            options={'verbose_name': 'Warranty Value', 'verbose_name_plural': 'Warranty Values'},
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_units', to='item_master.attributetype', verbose_name='Attribute Type'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='attribute_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='item_master.attributeunit', verbose_name='Attribute Unit'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default unit for this attribute type?', verbose_name='Is Default'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='symbol',
            field=models.CharField(max_length=10, unique=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='in_used',
            field=models.BooleanField(default=False, verbose_name='In Use'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='item_master.itemmaster', verbose_name='Item Master'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='production_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Production Date'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to=item_master.models.get_qrcode_upload_path, verbose_name='QR Code Image'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.attributetype', verbose_name='Attribute Type'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='item_master.inventoryitem', verbose_name='Inventory Item'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.attributeunit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='value',
            field=models.CharField(max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item_master.itemmaster', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='url',
            field=models.ImageField(upload_to='item_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item_master.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='service_forms',
            field=models.ManyToManyField(blank=True, to='item_master.serviceform', verbose_name='Service Forms'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='service_periods',
            field=models.ManyToManyField(blank=True, help_text='Service periods applicable for this product', through='item_master.MaintenanceSchedule', to='item_master.serviceperiodvalue', verbose_name='Service Periods'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='shortcode',
            field=models.CharField(max_length=10, unique=True, verbose_name='Short Code'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='spare_parts',
            field=models.ManyToManyField(blank=True, through='item_master.ItemSparePart', through_fields=('main_item', 'spare_part_item'), to='item_master.itemmaster', verbose_name='Spare Parts'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='stock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.stocktype', verbose_name='Stock Type'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='warranties',
            field=models.ManyToManyField(blank=True, to='item_master.warrantyvalue', verbose_name='Warranties'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='main_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_item_spare_parts_set', to='item_master.itemmaster', verbose_name='Main Item'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='spare_part_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_of_items_set', to='item_master.itemmaster', verbose_name='Spare Part Item'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='item_master.itemmaster', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='url',
            field=models.FileField(unique=True, upload_to='item_specs/', verbose_name='Specification File'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='is_critical',
            field=models.BooleanField(default=True, help_text='Is this a critical maintenance?', verbose_name='Is Critical'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='item_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='item_master.itemmaster', verbose_name='Item Master'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='maintenance_description',
            field=models.TextField(blank=True, help_text='Maintenance description', verbose_name='Maintenance Description'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='service_period_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.serviceperiodvalue', verbose_name='Service Period Value'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='type',
            field=models.CharField(help_text='Example: Monthly, Working hours based, Kilometer based', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='unit',
            field=models.CharField(help_text='Example: month, hour, km', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='service_period_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.serviceperiodtype', verbose_name='Service Period Type'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='value',
            field=models.FloatField(help_text='Example: 6 months, 3000 hours, 10000 km', verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='warrantytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='warrantytype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='warrantytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='warrantyvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='warrantyvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='warrantyvalue',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='warrantyvalue',
            name='warranty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.warrantytype', verbose_name='Warranty Type'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitemattribute',
            unique_together={('inventory_item', 'attribute_type')},
        ),
    ]
