# Generated by Django 5.2.1 on 2025-07-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0012_alter_inventoryitemattribute_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='value',
            field=models.PositiveIntegerField(help_text='Servis periyodu değeri (maksimum 4 haneli pozitif sayı). Örn: 6, 3000, 9999'),
        ),
        migrations.AlterField(
            model_name='warrantyvalue',
            name='value',
            field=models.PositiveIntegerField(help_text='Garanti değeri (maksimum 4 haneli pozitif sayı)'),
        ),
        migrations.AddConstraint(
            model_name='serviceperiodvalue',
            constraint=models.CheckConstraint(condition=models.Q(('value__lte', 9999)), name='service_period_value_max_4_digits'),
        ),
        migrations.AddConstraint(
            model_name='warrantyvalue',
            constraint=models.CheckConstraint(condition=models.Q(('value__lte', 9999)), name='warranty_value_max_4_digits'),
        ),
    ]
