# Generated by Django 5.2.4 on 2025-07-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0012_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitemattribute',
            unique_together={('inventory_item', 'attribute_type', 'unit')},
        ),
    ]
