# Generated by Django 5.2.1 on 2025-08-02 03:53

import django.db.models.deletion
import item_master.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0013_alter_serviceperiodvalue_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetype',
            options={'ordering': ['name'], 'verbose_name': 'Özellik Türü', 'verbose_name_plural': 'Özellik Türleri'},
        ),
        migrations.AlterModelOptions(
            name='attributetypeunit',
            options={'ordering': ['attribute_type__name', '-is_default', 'attribute_unit__name'], 'verbose_name': 'Özellik Türü Birimi', 'verbose_name_plural': 'Özellik Türü Birimleri'},
        ),
        migrations.AlterModelOptions(
            name='attributeunit',
            options={'ordering': ['name'], 'verbose_name': 'Özellik Birimi', 'verbose_name_plural': 'Özellik Birimleri'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name__shortcode', 'serial_no'], 'verbose_name': 'Stok Ürünü', 'verbose_name_plural': 'Stok Ürünleri'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitemattribute',
            options={'ordering': ['attribute_type__name'], 'verbose_name': 'Ürün Özelliği', 'verbose_name_plural': 'Ürün Özellikleri'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Ürün Resmi', 'verbose_name_plural': 'Ürün Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='itemmaster',
            options={'ordering': ['name'], 'verbose_name': 'Ana Ürün', 'verbose_name_plural': 'Ana Ürün'},
        ),
        migrations.AlterModelOptions(
            name='itemsparepart',
            options={'verbose_name': 'Yedek Parça', 'verbose_name_plural': 'Yedek Parçalar'},
        ),
        migrations.AlterModelOptions(
            name='itemspec',
            options={'ordering': ['created_at'], 'verbose_name': 'Ürün Özelliği Dosyası', 'verbose_name_plural': 'Ürün Özelliği Dosyaları'},
        ),
        migrations.AlterModelOptions(
            name='serviceform',
            options={'ordering': ['name'], 'verbose_name': 'Servis Formu', 'verbose_name_plural': 'Servis Formları'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status'], 'verbose_name': 'Statü', 'verbose_name_plural': 'Statüler'},
        ),
        migrations.AlterModelOptions(
            name='stocktype',
            options={'ordering': ['name'], 'verbose_name': 'Stok Türü', 'verbose_name_plural': 'Stok Türleri'},
        ),
        migrations.AlterModelOptions(
            name='warrantytype',
            options={'ordering': ['type'], 'verbose_name': 'Garanti Türü', 'verbose_name_plural': 'Garanti Türleri'},
        ),
        migrations.AlterModelOptions(
            name='warrantyvalue',
            options={'verbose_name': 'Garanti Değeri', 'verbose_name_plural': 'Garanti Değerleri'},
        ),
        migrations.RemoveConstraint(
            model_name='warrantyvalue',
            name='warranty_value_max_4_digits',
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Attribute Type Name'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_units', to='item_master.attributetype', verbose_name='Özellik Türü'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='attribute_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='item_master.attributeunit', verbose_name='Özellik Birimi'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default unit for this attribute type?', verbose_name='Varsayılan mı?'),
        ),
        migrations.AlterField(
            model_name='attributetypeunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Attribute Unit Name'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='symbol',
            field=models.CharField(max_length=10, unique=True, verbose_name='Attribute Unit Symbol'),
        ),
        migrations.AlterField(
            model_name='attributeunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Brand Image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='in_used',
            field=models.BooleanField(default=False, verbose_name='Kullanımda'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='item_master.itemmaster', verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='production_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Üretim Tarihi'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to=item_master.models.get_qrcode_upload_path, verbose_name='QR Kodu'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seri No'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.attributetype', verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='item_master.inventoryitem', verbose_name='Stok Ürünü'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.attributeunit', verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='inventoryitemattribute',
            name='value',
            field=models.CharField(max_length=255, null=True, verbose_name='Değer'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item_master.itemmaster', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='url',
            field=models.ImageField(upload_to='item_images/', verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.brand', verbose_name='Marka Adı'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item_master.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='service_forms',
            field=models.ManyToManyField(blank=True, to='item_master.serviceform', verbose_name='Servis Formları'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='service_periods',
            field=models.ManyToManyField(blank=True, help_text='Bu ürün için geçerli servis periyotları', through='item_master.MaintenanceSchedule', to='item_master.serviceperiodvalue', verbose_name='Servis Periyotları'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='shortcode',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kısa Kod'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='spare_parts',
            field=models.ManyToManyField(blank=True, help_text='Bu ürünün yedek parçaları', through='item_master.ItemSparePart', through_fields=('main_item', 'spare_part_item'), to='item_master.itemmaster', verbose_name='Yedek Parçalar'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.status', verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='stock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.stocktype', verbose_name='Stok Türü'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='warranties',
            field=models.ManyToManyField(blank=True, to='item_master.warrantyvalue', verbose_name='Garanti Değerleri'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='main_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_item_spare_parts_set', to='item_master.itemmaster', verbose_name='Main Item'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='spare_part_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_of_items_set', to='item_master.itemmaster', verbose_name='Spare Part Item'),
        ),
        migrations.AlterField(
            model_name='itemsparepart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='item_master.itemmaster', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='itemspec',
            name='url',
            field=models.FileField(unique=True, upload_to='item_specs/', verbose_name='Specification URL'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='is_critical',
            field=models.BooleanField(default=True, help_text='Kritik bakım mı?', verbose_name='Is Critical'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='item_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='item_master.itemmaster', verbose_name='Item Master'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='maintenance_description',
            field=models.TextField(blank=True, help_text='Bakım açıklaması', verbose_name='Maintenance Description'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='service_period_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.serviceperiodvalue', verbose_name='Service Period Value'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Service Form Name'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='type',
            field=models.CharField(help_text='Örn: Ay bazlı, Çalışma saati bazlı, Kilometre bazlı', max_length=100, verbose_name='Service Period Type'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='unit',
            field=models.CharField(help_text='Örn: ay, saat, km', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='serviceperiodtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='description',
            field=models.CharField(blank=True, help_text='Opsiyonel açıklama', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='service_period_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.serviceperiodtype', verbose_name='Service Period Type'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceperiodvalue',
            name='value',
            field=models.PositiveIntegerField(help_text='Servis periyodu değeri (maksimum 4 haneli pozitif sayı). Örn: 6, 3000, 9999', verbose_name='Service Period Value'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Stock Type'),
        ),
        migrations.AlterField(
            model_name='warrantytype',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Warranty Type'),
        ),
        migrations.AlterField(
            model_name='warrantyvalue',
            name='value',
            field=models.PositiveIntegerField(help_text='Garanti değeri (maksimum 4 haneli pozitif sayı)', verbose_name='Warranty Value'),
        ),
        migrations.AlterField(
            model_name='warrantyvalue',
            name='warranty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.warrantytype', verbose_name='Warranty Type'),
        ),
        migrations.AddConstraint(
            model_name='warrantytype',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_warranty_type'),
        ),
    ]
