# Generated by Django 5.2.4 on 2025-07-21 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0007_alter_workinghours_daily_working_hours'),
        ('item_master', '0009_serviceperiodtype_serviceperiodvalue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the installation was completed', verbose_name='Setup Date')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS latitude coordinate', max_digits=10, null=True, verbose_name='Latitude')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS longitude coordinate', max_digits=11, null=True, verbose_name='Longitude')),
                ('location_address', models.TextField(blank=True, help_text='Detailed address of installation location', verbose_name='Installation Address')),
                ('installation_notes', models.TextField(blank=True, help_text='Additional notes about the installation', verbose_name='Installation Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='End user customer where equipment is installed', limit_choices_to={'company_type': 'enduser'}, on_delete=django.db.models.deletion.PROTECT, to='customer.company', verbose_name='Customer')),
                ('inventory_item', models.ForeignKey(help_text='Commercial inventory item being installed', limit_choices_to={'item_master__stock_type': 'ticari'}, on_delete=django.db.models.deletion.PROTECT, to='item_master.inventoryitem', verbose_name='Inventory Item')),
                ('user', models.ForeignKey(help_text='User who performed the installation', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Installer User')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ['-setup_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('time_term', 'Time-Term Service (Month Based)'), ('working_hours', 'Working Hours Service')], max_length=20, verbose_name='Service Type')),
                ('service_value', models.DecimalField(decimal_places=2, help_text='Months for time-term service, Hours for working hours service', max_digits=10, verbose_name='Service Value')),
                ('next_service_date', models.DateTimeField(help_text='Calculated next service date', verbose_name='Next Service Date')),
                ('is_completed', models.BooleanField(default=False, help_text='Mark as completed when service is done', verbose_name='Service Completed')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('calculation_notes', models.TextField(blank=True, help_text='Details about how the service date was calculated', verbose_name='Calculation Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_followups', to='warranty_and_services.installation', verbose_name='Installation')),
            ],
            options={
                'verbose_name': 'Service Follow-Up',
                'verbose_name_plural': 'Service Follow-Ups',
                'ordering': ['next_service_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_type', models.CharField(choices=[('time_term', 'Time-Term Warranty (Year Based)'), ('working_hours', 'Working Hours Warranty')], max_length=20, verbose_name='Warranty Type')),
                ('warranty_value', models.DecimalField(decimal_places=2, help_text='Years for time-term warranty, Hours for working hours warranty', max_digits=10, verbose_name='Warranty Value')),
                ('end_of_warranty_date', models.DateTimeField(help_text='Calculated warranty end date', verbose_name='End of Warranty Date')),
                ('calculation_notes', models.TextField(blank=True, help_text='Details about how the warranty end date was calculated', verbose_name='Calculation Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_followups', to='warranty_and_services.installation', verbose_name='Installation')),
            ],
            options={
                'verbose_name': 'Warranty Follow-Up',
                'verbose_name_plural': 'Warranty Follow-Ups',
                'ordering': ['end_of_warranty_date'],
                'unique_together': {('installation', 'warranty_type', 'warranty_value')},
            },
        ),
    ]
