# Generated by Django 5.2.4 on 2025-07-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0009_serviceperiodtype_serviceperiodvalue_and_more'),
        ('warranty_and_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='inventory_item',
            field=models.ForeignKey(help_text='Commercial inventory item being installed', limit_choices_to={'name__stock_type__name': 'ticari'}, on_delete=django.db.models.deletion.PROTECT, to='item_master.inventoryitem', verbose_name='Inventory Item'),
        ),
    ]
