# Generated by Django 5.2.4 on 2025-07-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0009_serviceperiodtype_serviceperiodvalue_and_more'),
        ('warranty_and_services', '0002_alter_installation_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='inventory_item',
            field=models.ForeignKey(help_text='Commercial inventory item being installed (not in use)', limit_choices_to={'in_used': False, 'name__stock_type__name': 'ticari'}, on_delete=django.db.models.deletion.PROTECT, to='item_master.inventoryitem', verbose_name='Inventory Item'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='setup_date',
            field=models.DateTimeField(help_text='Date and time when the installation was completed', verbose_name='Setup Date'),
        ),
    ]
