# Generated by Django 5.2.4 on 2025-07-21 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0003_alter_installation_inventory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='setup_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the installation was completed', verbose_name='Setup Date'),
        ),
    ]
