# Generated by Django 5.2.4 on 2025-07-21 14:53

import django.db.models.deletion
import warranty_and_services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0009_serviceperiodtype_serviceperiodvalue_and_more'),
        ('warranty_and_services', '0004_alter_installation_setup_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='inventory_item',
            field=models.ForeignKey(help_text='Available inventory item to be installed', limit_choices_to={'in_used': False}, on_delete=django.db.models.deletion.PROTECT, to='item_master.inventoryitem', verbose_name='Inventory Item'),
        ),
        migrations.CreateModel(
            name='InstallationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Document related to the installation', upload_to=warranty_and_services.models.installation_document_upload_path, verbose_name='Installation Document')),
                ('title', models.CharField(help_text='Descriptive title for the document', max_length=200, verbose_name='Document Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the document content', verbose_name='Document Description')),
                ('document_type', models.CharField(choices=[('manual', 'Installation Manual'), ('certificate', 'Installation Certificate'), ('report', 'Installation Report'), ('checklist', 'Installation Checklist'), ('warranty', 'Warranty Document'), ('specification', 'Technical Specification'), ('contract', 'Installation Contract'), ('invoice', 'Invoice/Receipt'), ('other', 'Other Document')], default='report', max_length=50, verbose_name='Document Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('file_extension', models.CharField(blank=True, max_length=10, verbose_name='File Extension')),
                ('is_required', models.BooleanField(default=False, help_text='Mark as required document for this installation', verbose_name='Required Document')),
                ('is_confidential', models.BooleanField(default=False, help_text='Mark as confidential document (restricted access)', verbose_name='Confidential')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warranty_and_services.installation', verbose_name='Installation')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Installation Document',
                'verbose_name_plural': 'Installation Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo taken during installation', upload_to=warranty_and_services.models.installation_image_upload_path, verbose_name='Installation Image')),
                ('title', models.CharField(blank=True, help_text='Descriptive title for the image', max_length=200, verbose_name='Image Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what the image shows', verbose_name='Image Description')),
                ('image_type', models.CharField(choices=[('before', 'Before Installation'), ('during', 'During Installation'), ('after', 'After Installation'), ('equipment', 'Equipment Photo'), ('location', 'Location Photo'), ('documentation', 'Documentation Photo'), ('other', 'Other')], default='during', max_length=50, verbose_name='Image Type')),
                ('captured_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was taken', verbose_name='Captured At')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warranty_and_services.installation', verbose_name='Installation')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the image', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Installation Image',
                'verbose_name_plural': 'Installation Images',
                'ordering': ['-captured_at'],
            },
        ),
    ]
