# Generated by Django 5.2.4 on 2025-07-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0005_alter_installation_inventory_item_and_more'),
    ]

    operations = [
    ]
