# Generated by Django 5.2.4 on 2025-07-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0009_serviceperiodtype_serviceperiodvalue_and_more'),
        ('warranty_and_services', '0006_auto_20250721_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='inventory_item',
            field=models.ForeignKey(help_text='Inventory item to be installed', on_delete=django.db.models.deletion.PROTECT, to='item_master.inventoryitem', verbose_name='Inventory Item'),
        ),
    ]
