# Generated by Django 5.2.4 on 2025-07-23 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0009_serviceperiodtype_serviceperiodvalue_and_more'),
        ('warranty_and_services', '0007_alter_installation_inventory_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefollowup',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes about the completed service', verbose_name='Completion Notes'),
        ),
        migrations.AlterField(
            model_name='servicefollowup',
            name='service_type',
            field=models.CharField(choices=[('time_term', 'Time-Term Service (Month Based)'), ('working_hours', 'Working Hours Service'), ('maintenance', 'Maintenance/Repair Service')], max_length=20, verbose_name='Service Type'),
        ),
        migrations.CreateModel(
            name='ServiceFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('periodic', 'Periyodik Bakım'), ('arizi', 'Arızi Bakım')], max_length=20)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_spare_parts', models.ManyToManyField(blank=True, to='item_master.itemsparepart')),
                ('checked_controls', models.ManyToManyField(blank=True, to='item_master.serviceform')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warranty_and_services.installation')),
                ('service_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warranty_and_services.servicefollowup')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFormEntryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='service_form_documents/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_form_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warranty_and_services.serviceformentry')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFormEntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_form_images/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_form_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warranty_and_services.serviceformentry')),
            ],
        ),
    ]
