# Generated by Django 5.2.4 on 2025-07-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0008_servicefollowup_completion_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceformentry',
            name='service_type',
            field=models.CharField(choices=[('PERIODIC', 'Periyodik Bakım'), ('BREAKDOWN', 'Arıza'), ('REPLACEMENT', 'Parça Değişimi'), ('INSTALLATION', 'Kurulum'), ('OTHER', 'Diğer'), ('periodic', 'Periyodik Bakım'), ('arizi', 'Arızi Bakım')], max_length=20),
        ),
    ]
