# Generated by Django 5.2.1 on 2025-07-24 12:07

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0010_remove_serviceformentry_changed_spare_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when maintenance was performed', verbose_name='Service Date'),
            preserve_default=False,
        ),
    ]
