# Generated by Django 5.2.1 on 2025-07-28 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0011_maintenancerecord_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='setup_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the installation was completed', verbose_name='Setup Date'),
        ),
        migrations.AlterField(
            model_name='installationdocument',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='installationimage',
            name='captured_at',
            field=models.DateField(auto_now_add=True, help_text='When the photo was taken', verbose_name='Captured At'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_date',
            field=models.DateField(auto_now_add=True, verbose_name='Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='servicefollowup',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='servicefollowup',
            name='next_service_date',
            field=models.DateField(help_text='Calculated next service date', verbose_name='Next Service Date'),
        ),
        migrations.AlterField(
            model_name='warrantyfollowup',
            name='end_of_warranty_date',
            field=models.DateField(help_text='Calculated warranty end date', verbose_name='End of Warranty Date'),
        ),
    ]
