# Generated by Django 5.2.1 on 2025-07-28 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0011_maintenancerecord_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='setup_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when the installation was completed', null=True, verbose_name='Setup Date'),
        ),
    ]
