# Generated by Django 5.2.1 on 2025-07-28 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0012_alter_installation_setup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='setup_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the installation was completed', verbose_name='Setup Date'),
        ),
        migrations.AlterField(
            model_name='servicefollowup',
            name='service_value',
            field=models.PositiveIntegerField(help_text='Months for time-term service, Hours for working hours service', verbose_name='Service Value'),
        ),
        migrations.AlterField(
            model_name='warrantyfollowup',
            name='warranty_value',
            field=models.PositiveIntegerField(help_text='Years for time-term warranty, Hours for working hours warranty', verbose_name='Warranty Value'),
        ),
    ]
