# Generated by Django 5.2.1 on 2025-07-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0013_alter_installation_setup_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mechanical', 'Mechanical Failures'), ('electrical', 'Electrical Failures'), ('hydraulic', 'Hydraulic Failures'), ('pneumatic', 'Pneumatic Failures')], help_text='Type of breakdown category', max_length=50, unique=True, verbose_name='Category Type')),
                ('name', models.CharField(help_text='Category name', max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and can be selected', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breakdown Category',
                'verbose_name_plural': 'Breakdown Categories',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='BreakdownReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Breakdown reason name', max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this breakdown reason is active and can be selected', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breakdown Reason',
                'verbose_name_plural': 'Breakdown Reasons',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='breakdown_reason_detail',
            field=models.TextField(blank=True, help_text='Additional details about the breakdown reason', verbose_name='Breakdown Reason Detail'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='breakdown_reason',
            field=models.TextField(blank=True, help_text='This field will be removed in future migration', null=True, verbose_name='Old Breakdown Reason (Deprecated)'),
        ),
        migrations.AlterField(
            model_name='warrantyfollowup',
            name='warranty_type',
            field=models.CharField(choices=[('time_term', 'Time-Term Warranty (Month Based)'), ('working_hours', 'Working Hours Warranty')], max_length=20, verbose_name='Warranty Type'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the breakdown (required for breakdown maintenance)', null=True, on_delete=django.db.models.deletion.CASCADE, to='warranty_and_services.breakdowncategory', verbose_name='Breakdown Category'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='breakdown_reason_selected',
            field=models.ForeignKey(blank=True, help_text='Select breakdown reason (required for breakdown maintenance)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warranty_and_services.breakdownreason', verbose_name='Breakdown Reason'),
        ),
    ]
