# Generated by Django 5.2.1 on 2025-07-29 11:31

from django.db import migrations


def populate_breakdown_data(apps, schema_editor):
    """Populate initial breakdown categories and reasons"""
    BreakdownCategory = apps.get_model('warranty_and_services', 'BreakdownCategory')
    BreakdownReason = apps.get_model('warranty_and_services', 'BreakdownReason')
    
    # Create breakdown categories
    categories = [
        {'type': 'mechanical', 'name': 'Mekanik Arızalar'},
        {'type': 'electrical', 'name': 'Elektrik Arızaları'},
        {'type': 'hydraulic', 'name': 'Hidrolik Arızalar'},
        {'type': 'pneumatic', 'name': 'Pnömatik Arızalar'},
    ]
    
    for cat_data in categories:
        BreakdownCategory.objects.get_or_create(
            type=cat_data['type'],
            defaults={'name': cat_data['name']}
        )
    
    # Create some example breakdown reasons
    reasons = [
        'Motor arızası',
        'Kayış kopması',
        'Rulman arızası',  
        'Şaft kırılması',
        'Elektrik kaçağı',
        'Sigorta atması',
        'Kontaktör arızası',
        'Kablo hasarı',
        'Hortum patlaması',
        'Valf arızası',
        'Pompa arızası',
        'Filtre tıkanması',
        'Hava kaçağı',
        'Basınç düşüklüğü',
        'Kompresör arızası',
        'Manometre arızası',
    ]
    
    for reason_name in reasons:
        BreakdownReason.objects.get_or_create(
            name=reason_name,
            defaults={'is_active': True}
        )


def reverse_populate_breakdown_data(apps, schema_editor):
    """Remove populated breakdown data"""
    BreakdownCategory = apps.get_model('warranty_and_services', 'BreakdownCategory')
    BreakdownReason = apps.get_model('warranty_and_services', 'BreakdownReason')
    
    BreakdownReason.objects.all().delete()
    BreakdownCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('warranty_and_services', '0014_add_breakdown_models_and_update_maintenance'),
    ]

    operations = [
        migrations.RunPython(populate_breakdown_data, reverse_populate_breakdown_data),
    ]
